name: Build Docker Image from MLflow Model URI, Push to Docker Hub, and Update EC2

on:
  repository_dispatch:
    types: [new-model-version]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: prod

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: deploy docker to ec2
      uses: appleboy/ssh-action@master
      with: 
        host: ec2-54-79-227-23.ap-southeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new"
          docker run -d --name sentiment -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -p 8501:8501 "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new"
      

